In [26]:

import pandas as pd
import sqlite3

# Read the CSV file into a DataFrame                                               
df = pd.read_csv('country.csv')

# Create a connection to the SQLite database
conn = sqlite3.connect('database.db')

# Use the DataFrame.to_sql() method to create a new table in the database and populate it with the data from the DataFrame
df.to_sql('country', conn, if_exists='replace', index=False)

48564

In [24]:
# pip install ipython-sql

In [27]:
df = pd.read_csv('Match.csv')
df.to_sql('Match', conn, if_exists='replace', index=False)

48564

In [28]:
df = pd.read_csv('Medal_type.csv')
df.to_sql('Medal_type', conn, if_exists='replace', index=False)

48564

In [29]:
df = pd.read_csv('Player.csv')
df.to_sql('Player', conn, if_exists='replace', index=False)

48564

In [30]:
%load_ext sql
%sql sqlite:///database.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [31]:
%%sql
select*
from Match
limit 20;

 * sqlite:///database.db
Done.

[(4, 'Calgary', "Speed Skating Women's 500 metres", 'Speed Skating'),
 (5, 'Calgary', "Speed Skating Women's 1,000 metres", 'Speed Skating'),
 (6, 'Albertville', "Speed Skating Women's 500 metres", 'Speed Skating'),
 (7, 'Albertville', "Speed Skating Women's 1,000 metres", 'Speed Skating'),
 (8, 'Lillehammer', "Speed Skating Women's 500 metres", 'Speed Skating'),
 (9, 'Lillehammer', "Speed Skating Women's 1,000 metres", 'Speed Skating'),
 (10, 'Albertville', "Cross Country Skiing Men's 10 kilometres", 'Cross Country Skiing'),
 (11, 'Albertville', "Cross Country Skiing Men's 50 kilometres", 'Cross Country Skiing'),
 (12, 'Albertville', "Cross Country Skiing Men's 10/15 kilometres Pursuit", 'Cross Country Skiing'),
 (13, 'Albertville', "Cross Country Skiing Men's 4 x 10 kilometres Relay", 'Cross Country Skiing'),
 (14, 'Lillehammer', "Cross Country Skiing Men's 10 kilometres", 'Cross Country Skiing'),
 (15, 'Lillehammer', "Cross Country Skiing Men's 30 kilometres", 'Cross Country Skiing'),
 (16, 'Lillehammer', "Cross Country Skiing Men's 10/15 kilometres Pursuit", 'Cross Country Skiing'),
 (17, 'Lillehammer', "Cross Country Skiing Men's 4 x 10 kilometres Relay", 'Cross Country Skiing'),
 (18, 'Albertville', "Cross Country Skiing Men's 10 kilometres", 'Cross Country Skiing'),
 (19, 'Albertville', "Cross Country Skiing Men's 50 kilometres", 'Cross Country Skiing'),
 (20, 'Albertville', "Cross Country Skiing Men's 10/15 kilometres Pursuit", 'Cross Country Skiing'),
 (21, 'Albertville', "Cross Country Skiing Men's 4 x 10 kilometres Relay", 'Cross Country Skiing'),
 (22, 'Lillehammer', "Cross Country Skiing Men's 10 kilometres", 'Cross Country Skiing'),
 (23, 'Lillehammer', "Cross Country Skiing Men's 30 kilometres", 'Cross Country Skiing')]

In [32]:
%%sql
select*
from Player
limit 10;

 * sqlite:///database.db
Done.

[(4, 'Christine Jacoba Aaftink', 'F', 21.0),
 (5, 'Christine Jacoba Aaftink', 'F', 21.0),
 (6, 'Christine Jacoba Aaftink', 'F', 25.0),
 (7, 'Christine Jacoba Aaftink', 'F', 25.0),
 (8, 'Christine Jacoba Aaftink', 'F', 27.0),
 (9, 'Christine Jacoba Aaftink', 'F', 27.0),
 (10, 'Per Knut Aaland', 'M', 31.0),
 (11, 'Per Knut Aaland', 'M', 31.0),
 (12, 'Per Knut Aaland', 'M', 31.0),
 (13, 'Per Knut Aaland', 'M', 31.0)]

In [9]:
%%sql
select*
from country
limit 20;

 * sqlite:///database.db
Done.

[(4, 'Netherlands', 'NED'),
 (5, 'Netherlands', 'NED'),
 (6, 'Netherlands', 'NED'),
 (7, 'Netherlands', 'NED'),
 (8, 'Netherlands', 'NED'),
 (9, 'Netherlands', 'NED'),
 (10, 'United States', 'USA'),
 (11, 'United States', 'USA'),
 (12, 'United States', 'USA'),
 (13, 'United States', 'USA'),
 (14, 'United States', 'USA'),
 (15, 'United States', 'USA'),
 (16, 'United States', 'USA'),
 (17, 'United States', 'USA'),
 (18, 'United States', 'USA'),
 (19, 'United States', 'USA'),
 (20, 'United States', 'USA'),
 (21, 'United States', 'USA'),
 (22, 'United States', 'USA'),
 (23, 'United States', 'USA')]

In [10]:
%%sql
select*
from Medal_type
limit 20;

 * sqlite:///database.db
Done.

[(4, 1988, None),
 (5, 1988, None),
 (6, 1992, None),
 (7, 1992, None),
 (8, 1994, None),
 (9, 1994, None),
 (10, 1992, None),
 (11, 1992, None),
 (12, 1992, None),
 (13, 1992, None),
 (14, 1994, None),
 (15, 1994, None),
 (16, 1994, None),
 (17, 1994, None),
 (18, 1992, None),
 (19, 1992, None),
 (20, 1992, None),
 (21, 1992, None),
 (22, 1994, None),
 (23, 1994, None)]

# This is a historical dataset on the modern Olympic Games, including all the Games from Chamonix 1924 to Sochi 2014.

# This dataset contains 48565 rows and we splitted it to 4 tables.

# Now we want to run some simple SQL queries

## 1-SQL query that selects all the distinct values of the "Sport" column.

In [16]:
%%sql
select distinct(sport)
from Match
order by sport;

 * sqlite:///database.db
Done.

[('Alpine Skiing',),
 ('Alpinism',),
 ('Biathlon',),
 ('Bobsleigh',),
 ('Cross Country Skiing',),
 ('Curling',),
 ('Figure Skating',),
 ('Freestyle Skiing',),
 ('Ice Hockey',),
 ('Luge',),
 ('Military Ski Patrol',),
 ('Nordic Combined',),
 ('Short Track Speed Skating',),
 ('Skeleton',),
 ('Ski Jumping',),
 ('Snowboarding',),
 ('Speed Skating',)]

## 2-SQL query that selects max and min ages of female players.

In [17]:
%%sql
select max(age),min(age)
from Player
where Sex='F' 
order by Age desc
limit 5;

 * sqlite:///database.db
Done.

[(48.0, 11.0)]

## 3-SQL query that selects total medals by year.

In [18]:
%%sql
select count(*) ,Medal,Year
from Medal_type
where medal is not null
group by medal,year
order by year desc
limit 20;

 * sqlite:///database.db
Done.

[(198, 'Bronze', 2014),
 (202, 'Gold', 2014),
 (197, 'Silver', 2014),
 (171, 'Bronze', 2010),
 (174, 'Gold', 2010),
 (175, 'Silver', 2010),
 (175, 'Bronze', 2006),
 (176, 'Gold', 2006),
 (175, 'Silver', 2006),
 (159, 'Bronze', 2002),
 (162, 'Gold', 2002),
 (157, 'Silver', 2002),
 (150, 'Bronze', 1998),
 (145, 'Gold', 1998),
 (145, 'Silver', 1998),
 (112, 'Bronze', 1994),
 (110, 'Gold', 1994),
 (109, 'Silver', 1994),
 (106, 'Bronze', 1992),
 (104, 'Gold', 1992)]

## 4-SQL query that selects the winers that recieved goal medals in 1998,return the name of participants,the country and the events.

In [12]:
%%sql
select Name,team,Event
from country,Medal_type,Match,Player
where country.team_id =Medal_type.player_id
And Medal_type.player_id=match.player_id
And match.player_id=player.player_id
And medal='Gold'
and year=1998;

 * sqlite:///database.db
Done.

[('Thomas Alsgaard (Alsgrd-)', 'Norway', "Cross Country Skiing Men's 10/15 kilometres Pursuit"),
 ('Thomas Alsgaard (Alsgrd-)', 'Norway', "Cross Country Skiing Men's 4 x 10 kilometres Relay"),
 ('An Sang-Mi', 'South Korea', "Short Track Speed Skating Women's 3,000 metres Relay"),
 ('Dominic Andres', 'Switzerland', "Curling Men's Curling"),
 ('Katrin Apel', 'Germany', "Biathlon Women's 4 x 7.5 kilometres Relay"),
 ('Christina "Chris" Bailey', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Laurie Baker (-Mutch)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('ric Bdard', 'Canada', "Short Track Speed Skating Men's 5,000 metres Relay"),
 ('Petra Behle-Schaaf', 'Germany', "Biathlon Women's 4 x 7.5 kilometres Relay"),
 ('Jan Behrendt', 'Germany-1', "Luge Mixed (Men)'s Doubles"),
 ('Josef Bernek', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Eric Bergoust', 'United States', "Freestyle Skiing Men's Aerials"),
 ('Janice "Jan" Betker', 'Canada', "Curling Women's Curling"),
 ('Ole Einar Bjrndalen', 'Norway', "Biathlon Men's 10 kilometres Sprint"),
 ('Alana Olga Blahoski', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Kenneth Braaten', 'Norway', "Nordic Combined Men's Team"),
 ('Elizabeth "Lisa" Brown-Miller', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Hans Petter Buraas', 'Norway', "Alpine Skiing Men's Slalom"),
 ('Karyn L. Bye (-Dietz)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Jan aloun', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Derrick Nathan Campbell', 'Canada', "Short Track Speed Skating Men's 5,000 metres Relay"),
 ('Yuliya Anatolyevna Chepalova', 'Russia', "Cross Country Skiing Women's 30 kilometres"),
 ('Deborah Compagnoni', 'Italy', "Alpine Skiing Women's Giant Slalom"),
 ('Colleen Coyne', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Jean-Luc Crtier', 'France', "Alpine Skiing Men's Downhill"),
 ('Ekaterina Stefanova Dafovska (-Prodanova)', 'Bulgaria', "Biathlon Women's 15 kilometres"),
 ('Olga Valeryevna Danilova', 'Russia', "Cross Country Skiing Women's 15 kilometres"),
 ('Olga Valeryevna Danilova', 'Russia', "Cross Country Skiing Women's 4 x 5 kilometres Relay"),
 ('Sara DeCosta (-Hayes)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Ursula "Uschi" Disl', 'Germany', "Biathlon Women's 4 x 7.5 kilometres Relay"),
 ('Artur Valeryevich Dmitriyev', 'Russia-1', 'Figure Skating Mixed Pairs'),
 ('Ji Dopita', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Franois Louis Drolet', 'Canada', "Short Track Speed Skating Men's 5,000 metres Relay"),
 ('Patricia "Tricia" Dunn-Luoma', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Sven Fischer', 'Germany', "Biathlon Men's 4 x 7.5 kilometres Relay"),
 ('Atina Ford (Johnston-)', 'Canada', "Curling Women's Curling"),
 ('Kazuyoshi Funaki', 'Japan', "Ski Jumping Men's Large Hill, Individual"),
 ('Kazuyoshi Funaki', 'Japan', "Ski Jumping Men's Large Hill, Team"),
 ('Marc Gagnon', 'Canada', "Short Track Speed Skating Men's 5,000 metres Relay"),
 ('Nina Vasilyevna Gavrylyuk', 'Russia', "Cross Country Skiing Women's 4 x 5 kilometres Relay"),
 ('Mathilde "Hilde" Gerg (-Gral)', 'Germany', "Alpine Skiing Women's Slalom"),
 ('Catherine Michelle "Cammi" Granato (-Ferraro)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Oksana Vladimirovna "Pasha" Grishchuk', 'Russia-1', 'Figure Skating Mixed Ice Dancing'),
 ('Ricco Gro', 'Germany', "Biathlon Men's 4 x 7.5 kilometres Relay"),
 ('Marcia Gudereit (Schiml-)', 'Canada', "Curling Women's Curling"),
 ('Georg Hackl', 'Germany', "Luge Men's Singles"),
 ('Olaf Hampel', 'Germany-2', "Bobsleigh Men's Four"),
 ('Roman Hamrlk', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Halvard Hanevold', 'Norway', "Biathlon Men's 20 kilometres"),
 ('Masahiko Harada', 'Japan', "Ski Jumping Men's Large Hill, Team"),
 ('Dominik Haek', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Milan Hejduk', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Gnther Huber', 'Italy-1', "Bobsleigh Men's Two"),
 ('Patrick Hrlimann', 'Switzerland', "Curling Men's Curling"),
 ('Jaromr Jgr', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Marco Jakobs', 'Germany-2', "Bobsleigh Men's Four"),
 ('Jeon I-Gyeong', 'South Korea', "Short Track Speed Skating Women's 1,000 metres"),
 ('Jeon I-Gyeong', 'South Korea', "Short Track Speed Skating Women's 3,000 metres Relay"),
 ('Erling Jevne', 'Norway', "Cross Country Skiing Men's 4 x 10 kilometres Relay"),
 ('Oksana Borisovna Kazakova', 'Russia-1', 'Figure Skating Mixed Pairs'),
 ('Kim Dong-Seong', 'South Korea', "Short Track Speed Skating Men's 1,000 metres"),
 ('Kim Yun-Mi', 'South Korea', "Short Track Speed Skating Women's 3,000 metres Relay"),
 ('Kathryn "Katie" King', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Stefan Kraue', 'Germany-1', "Luge Mixed (Men)'s Doubles"),
 ('Silke Kraushaar (-Pielach)', 'Germany', "Luge Women's Singles"),
 ('Frantiek Kuera', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Galina Alekseyevna Kukleva', 'Russia', "Biathlon Women's 7.5 kilometres Sprint"),
 ('Ilya Aleksandrovich Kulik', 'Russia', "Figure Skating Men's Singles"),
 ('Robert Lang', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Christoph Langen', 'Germany-2', "Bobsleigh Men's Four"),
 ('Larisa Yevgenyevna Lazutina (Ptitsyna-)', 'Russia', "Cross Country Skiing Women's 5 kilometres"),
 ('Larisa Yevgenyevna Lazutina (Ptitsyna-)', 'Russia', "Cross Country Skiing Women's 5/10 kilometres Pursuit"),
 ('Larisa Yevgenyevna Lazutina (Ptitsyna-)', 'Russia', "Cross Country Skiing Women's 4 x 5 kilometres Relay"),
 ('Catriona Ann Le May Doan', 'Canada', "Speed Skating Women's 500 metres"),
 ('Tara Kristen Lipinski (-Kapostasy)', 'United States', "Figure Skating Women's Singles"),
 ('Shelley Looney', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Patrik Lrtscher', 'Switzerland', "Curling Men's Curling"),
 ('Frank Luck', 'Germany', "Biathlon Men's 4 x 7.5 kilometres Relay"),
 ('Pierre Fritz Lueders', 'Canada-1', "Bobsleigh Men's Two"),
 ('Fred Brre Lundberg', 'Norway', "Nordic Combined Men's Team"),
 ('David G. "Dave" MacEachern', 'Canada-1', "Bobsleigh Men's Two"),
 ('Hermann Maier', 'Austria', "Alpine Skiing Men's Super G"),
 ('Hermann Maier', 'Austria', "Alpine Skiing Men's Giant Slalom"),
 ('Joan Elizabeth McCusker (Inglis-)', 'Canada', "Curling Women's Curling"),
 ('Suzanne "Sue" Merz', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Allison Jaime "A. J." Mleczko (-Griswold)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('David Moravec', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Jonathan "Jonny" Moseley', 'United States', "Freestyle Skiing Men's Moguls"),
 ('Tara Mounsey', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Victoria "Vicki" Movsessian (-Lamoriello)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Daniel Mller', 'Switzerland', "Curling Men's Curling"),
 ('Mika Kristian Myllyl', 'Finland', "Cross Country Skiing Men's 30 kilometres"),
 ('Gunda Niemann-Stirnemann-Kleemann', 'Germany', "Speed Skating Women's 3,000 metres"),
 ('Takafumi Nishitani', 'Japan', "Short Track Speed Skating Men's 500 metres"),
 ('Takanobu Okabe', 'Japan', "Ski Jumping Men's Large Hill, Team"),
 ('Pavel Patera', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Claudia Pechstein', 'Germany', "Speed Skating Women's 5,000 metres"),
 ('Annie Perreault', 'Canada', "Short Track Speed Skating Women's 500 metres"),
 ('Diego Perren', 'Switzerland', "Curling Men's Curling"),
 ('Yevgeny Arkadyevich Platov', 'Russia-1', 'Figure Skating Mixed Ice Dancing'),
 ('Ids Hylke Postma', 'Netherlands', "Speed Skating Men's 1,000 metres"),
 ('Libor Prochzka', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Martin Prochzka', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Ross Rebagliati', 'Canada', "Snowboarding Men's Giant Slalom"),
 ('Robert Reichel', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Mario Reiter', 'Austria', "Alpine Skiing Men's Combined"),
 ('Gianni Petrus Cornelis Romme', 'Netherlands', "Speed Skating Men's 5,000 metres"),
 ('Gianni Petrus Cornelis Romme', 'Netherlands', "Speed Skating Men's 10,000 metres"),
 ('Karine Martine Ruby', 'France', "Snowboarding Women's Giant Slalom"),
 ('Martin Ruinsk', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Angela Marie Ruggiero', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Vladimr Rika', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Hiroya Saito', 'Japan', "Ski Jumping Men's Large Hill, Team"),
 ('Tae Satoya', 'Japan', "Freestyle Skiing Women's Moguls"),
 ('Jennifer Lynn "Jenny" Schmidgall-Potter', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Sandra Marie Schmirler (-Peterson-)', 'Canada', "Curling Women's Curling"),
 ('Katja Seizinger (-Weber)', 'Germany', "Alpine Skiing Women's Downhill"),
 ('Katja Seizinger (-Weber)', 'Germany', "Alpine Skiing Women's Combined"),
 ('Peter Sendel', 'Germany', "Biathlon Men's 4 x 7.5 kilometres Relay"),
 ('Hiroyasu Shimizu', 'Japan', "Speed Skating Men's 500 metres"),
 ('Gian Simmen', 'Switzerland', "Snowboarding Men's Halfpipe"),
 ('Sture Sivertsen', 'Norway', "Cross Country Skiing Men's 4 x 10 kilometres Relay"),
 ('Halldor Skard, Jr.', 'Norway', "Nordic Combined Men's Team"),
 ('Ji lgr (Bubla-)', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Richard mehlk', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Jani Markus Soininen', 'Finland', "Ski Jumping Men's Normal Hill, Individual"),
 ('dne Sndrl', 'Norway', "Speed Skating Men's 1,500 metres"),
 ('Jaroslav paek', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Nicole "Nikki" Stone', 'United States', "Freestyle Skiing Women's Aerials"),
 ('Martin Straka', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Picabo Street', 'United States', "Alpine Skiing Women's Super G"),
 ('Petr Svoboda', 'Czech Republic', "Ice Hockey Men's Ice Hockey"),
 ('Antonio Tartaglia', 'Italy-1', "Bobsleigh Men's Two"),
 ('Nicola Thost', 'Germany', "Snowboarding Women's Halfpipe"),
 ('Maria Aaltje "Marianne" Timmer', 'Netherlands', "Speed Skating Women's 1,000 metres"),
 ('Maria Aaltje "Marianne" Timmer', 'Netherlands', "Speed Skating Women's 1,500 metres"),
 ('Sarah Tueting (-Lemaitre)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Gretchen Ulion (-Silverman)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Yelena Valeryevna Vlbe (Trubitsyna-)', 'Russia', "Cross Country Skiing Women's 4 x 5 kilometres Relay"),
 ('Bjarte Engen Vik', 'Norway', "Nordic Combined Men's Team"),
 ('Bjarte Engen Vik', 'Norway', "Nordic Combined Men's Individual"),
 ('Sandra Whyte (-Sweeney)', 'United States', "Ice Hockey Women's Ice Hockey"),
 ('Won Hye-Gyeong', 'South Korea', "Short Track Speed Skating Women's 3,000 metres Relay"),
 ('Martina Zellner (-Seidl)', 'Germany', "Biathlon Women's 4 x 7.5 kilometres Relay"),
 ('Markus Zimmermann', 'Germany-2', "Bobsleigh Men's Four")]

## 5-SQL query that selects the first and last years of winter olympics

In [19]:
%%sql
select min(year) as first_year, max(year) as last_year
from Medal_type;

 * sqlite:///database.db
Done.

[(1924, 2014)]

## 6-SQL query that selects the city where speed skating event was held in 1998

In [21]:
%%sql
select Distinct City as City,Sport
from Match
where player_id in(
select player_id 
from medal_type 
where sport='Speed Skating'
and year=1998)
limit 20;

 * sqlite:///database.db
Done.

[('Nagano', 'Speed Skating')]

## 7-SQL query that selects the count of events by year

In [11]:
%%sql
select year,count(event)
from Match,Medal_type 
where match.player_id=Medal_type.player_id
group by year
order by year asc;

 * sqlite:///database.db
Done.

[(1924, 460),
 (1928, 582),
 (1932, 352),
 (1936, 895),
 (1948, 1075),
 (1952, 1088),
 (1956, 1307),
 (1960, 1116),
 (1964, 1778),
 (1968, 1891),
 (1972, 1655),
 (1976, 1861),
 (1980, 1746),
 (1984, 2134),
 (1988, 2639),
 (1992, 3436),
 (1994, 3160),
 (1998, 3605),
 (2002, 4109),
 (2006, 4382),
 (2010, 4402),
 (2014, 4891)]

## 8-SQL query that selects the event in which women have participated most?

In [22]:
%%sql
select sex,event,count(sex) as max,Year
from Player,Match,Medal_type 
where Player.player_id=Match.player_id
and Player.player_id=Medal_type.player_id
and Sex='F'
group by Event
Order by max desc
limit 5;

 * sqlite:///database.db
Done.

[('F', "Alpine Skiing Women's Slalom", 966, 2014),
 ('F', "Alpine Skiing Women's Giant Slalom", 961, 1998),
 ('F', "Ice Hockey Women's Ice Hockey", 754, 2014),
 ('F', "Alpine Skiing Women's Downhill", 708, 1964),
 ('F', "Cross Country Skiing Women's 10 kilometres", 667, 1988)]

## 9- SQL query that selects top 5 sports in which female athletes are more interested ?
.

In [47]:
%%sql
select sport, COUNT(medal) AS medal_count,sex
from Match,Medal_type,player
where Match.player_id=Medal_type.player_id
and Match.player_id=player.player_id
and sex = 'F'
Group by sport
ORDER BY medal_count DESC
LIMIT 5;

 * sqlite:///database.db
Done.

[('Cross Country Skiing', 339, 'F'),
 ('Ice Hockey', 300, 'F'),
 ('Speed Skating', 242, 'F'),
 ('Alpine Skiing', 213, 'F'),
 ('Figure Skating', 179, 'F')]

## 10-SQL query that selects the team which has won the most gold medal in which year,return the count of medal and the year?

In [22]:
%%sql
select team,COUNT(Medal) AS medal_won,year
from country,Medal_type
where country.team_id=Medal_type.player_id
and medal IS NOT NULL
and medal='Gold'
GROUP BY team
ORDER BY medal_won DESC
LIMIT 1

 * sqlite:///database.db
Done.

[('Canada', 289, 1952)]

## 11-SQL query that selects the average age of female and male athletes who won a medal?

In [39]:
%%sql
select sex, AVG(age) AS avg_age
from Player,Medal_type
where Player.Player_id=Medal_type.Player_id
and medal IS NOT NULL
GROUP BY sex

 * sqlite:///database.db
Done.

[('F', 25.186637217007178), ('M', 26.47379292538084)]